version: "3.9"
services:
  ddns-ddnss:
    # build:
      # dockerfile: ./Dockerfile
    image: alcapone1933/ddns-ddnss:latest
    # image: alcapone1933/ddns-ddnss:v0.0.6
    container_name: ddns-ddnss
    restart: always
    # volumes:
      # - data:/data
    environment:
      - "TZ=Europe/Berlin"
      - "CRON_TIME=*/15 * * * *"
      - "CRON_TIME_DIG=*/30 * * * *"
      - "DOMAIN_DDNSS=deine-domain.ddnss.de"
      # - "DOMAIN_DDNSS=deine-domain.ddnss.de,deine-domain.ddnss.org"
      - "DOMAIN_KEY=1234567890abcdefghijklmnopqrstuv"
      - "IP_CHECK=Yes"
      # - "SHOUTRRR_URL="
      # - "SHOUTRRR_SKIP_TEST=no"
      # - "NAME_SERVER=ns1.ddnss.de"
      # - "PUID=1000"
      # - "PGID=1000"
# volumes:
  # data:
    # name: ddns-ddnss_data
